version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.deploy
    container_name: CPAS_backend
    env_file: .env
    command: gunicorn CPAS.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.deploy
    container_name: CPAS_frontend
    ports:
      - "80:80"
    depends_on:
      - backend