# Generated by Django 4.2.25 on 2025-10-16 13:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('disease_group', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CPAS_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('sub_region', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CPAS_Main.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CPAS_Main.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ProducedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_commodity_price', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CPAS_Main.crop')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CPAS_Main.season')),
            ],
            options={
                'unique_together': {('crop', 'season')},
            },
        ),
        migrations.CreateModel(
            name='DiseasePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_presence_status', models.CharField(max_length=2)),
                ('disease_incidence_year_percentage', models.FloatField()),
                ('disease_incidence_area_percentage', models.FloatField()),
                ('disease_severity_without_control_percentage', models.FloatField(null=True)),
                ('disease_severity_with_control_percentage', models.FloatField(null=True)),
                ('disease_severity_control_genetic_contribution_percentage', models.FloatField(null=True)),
                ('disease_severity_control_cultural_contribution_percentage', models.FloatField(null=True)),
                ('disease_severity_control_pesticide_contribution_percentage', models.FloatField(null=True)),
                ('fungicide_resistance_risk', models.CharField(max_length=3)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CPAS_Main.crop')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CPAS_Main.disease')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CPAS_Main.location')),
            ],
            options={
                'unique_together': {('disease', 'crop', 'location')},
            },
        ),
        migrations.CreateModel(
            name='CropArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_hectares', models.FloatField()),
                ('value_tonnes', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CPAS_Main.crop')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CPAS_Main.location')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CPAS_Main.season')),
            ],
            options={
                'unique_together': {('crop', 'location', 'season')},
            },
        ),
    ]
