# Generated by Django 4.2.24 on 2025-09-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPAS_Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cpas_user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cpas_user',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='cpas_user',
            name='username',
        ),
        migrations.AlterField(
            model_name='cpas_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
