# Generated by Django 4.2.24 on 2025-10-16 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPAS_Main', '0002_alter_cpas_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Crops',
            new_name='Crop',
        ),
        migrations.RenameField(
            model_name='croparea',
            old_name='sub_region',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='croparea',
            old_name='year',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='diseasepresence',
            old_name='sub_region',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='producedin',
            old_name='year',
            new_name='season',
        ),
        migrations.AlterUniqueTogether(
            name='croparea',
            unique_together={('crop', 'location', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='diseasepresence',
            unique_together={('disease', 'crop', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='producedin',
            unique_together={('crop', 'season')},
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CPAS_Main.region'),
        ),
    ]
