# Generated by Django 4.2.24 on 2025-09-29 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPAS_Main', '0003_region_alter_location_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crops',
            new_name='Crop',
        ),
    ]
