# Generated by Django 4.2.24 on 2025-09-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPAS_Main', '0004_rename_crops_crop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croparea',
            old_name='sub_region',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='croparea',
            old_name='year',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='diseasepresence',
            old_name='sub_region',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='producedin',
            old_name='year',
            new_name='season',
        ),
        migrations.AlterUniqueTogether(
            name='croparea',
            unique_together={('crop', 'location', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='diseasepresence',
            unique_together={('disease', 'crop', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='producedin',
            unique_together={('crop', 'season')},
        ),
    ]
